name: App Connect Template Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - run: touch package-lock.json
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        cache: 'npm'
    - run: npm i
    - run: npm test
